name: Generate Snake Animation

on:
  schedule: # 매일 자정(UTC 기준)에 자동 실행
    - cron: "0 0 * * *" 
  workflow_dispatch: # 수동으로 버튼을 눌러서 실행할 수 있게 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 스네이크 애니메이션 생성기
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # 생성된 이미지를 'output' 브랜치에 푸시
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
